# This is a fabricated policy to show all possible policy options.
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: all-options
spec:
  allowed:
    commonName:
      required: true
      value: "example.com"
      validations:
        - rule: self.endsWith('.com')
          message: CommonName must end with '.com'
    dnsNames:
      required: false
      values:
        - "example.com"
        - "*.example.com"
      validations:
        - rule: self.size() =< 24
          message: DNSName must be no more than 24 characters
    ipAddresses:
      required: false
      values: ["*"]
      validations:
        - rule: self.matches('\d+\.\d+\.\d+\.\d+')
          message: IPAddress must be a valid IPv4 address
    uris:
      required: false
      values:
        - "spiffe://example.org/ns/*/sa/*"
      validations:
        - rule: self.startsWith('spiffe://%s/ns/%s/sa/'.format(['example.org',cr.namespace]))
          message: URI must be a valid SPIFFE ID in trust domain bound to request namespace
    emailAddresses:
      required: false
      values:
        - "*@example.com"
      validations:
        - rule: self.size() =< 24
          message: EmailAddress must be no more than 24 characters
    isCA: false
    usages:
      - "server auth"
      - "client auth"
    subject:
      organizations:
        required: false
        values: ["*"]
        validations:
          - rule: self.size() > 0
            message: must not be empty
      countries:
        required: false
        values: ["*"]
        validations:
          - rule: self.size() > 0
            message: must not be empty
      organizationalUnits:
        required: false
        values: ["*"]
        validations:
          - rule: self.size() > 0
            message: must not be empty
      localities:
        required: false
        values: ["*"]
        validations:
          - rule: self.size() > 0
            message: must not be empty
      provinces:
        required: false
        values: ["*"]
        validations:
          - rule: self.size() > 0
            message: must not be empty
      streetAddresses:
        required: false
        values: ["*"]
        validations:
          - rule: self.size() > 0
            message: must not be empty
      postalCodes:
        required: false
        values: ["*"]
        validations:
          - rule: self.size() > 0
            message: must not be empty
      serialNumber:
        required: false
        value: "*"
        validations:
          - rule: self.size() > 0
            message: must not be empty
  constraints:
    minDuration: 1h
    maxDuration: 24h
    privateKey:
      algorithm: RSA
      minSize: 2048
      maxSize: 4096
  plugins:
    rego:
      values:
        my-ref: "hello-world"
  selector:
    issuerRef:
      name: "my-ca-*"
      kind: "*Issuer"
      group: cert-manager.io
