# Here we match on all requests created by anyone. The policy contains an
# impossible condition and so will always return denied. This ensures all
# requests will be denied by default unless another policy permits the request.
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: deny-all
spec:
  allowed:
    dnsNames:
      values: []
      required: true
  selector:
    issuerRef: {}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-policy:deny-all
rules:
- apiGroups: ["policy.cert-manager.io"]
  resources: ["certificaterequestpolicies"]
  verbs: ["use"]
  resourceNames: ["deny-all"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-policy:deny-all
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-policy:deny-all
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
