apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: example-com
spec:
  allowed:
    commonName:
      value: "example.com"
    dnsNames:
      values:
        - "example.com"
        - "*.example.com"
      validations:
        - rule: !self.contains('*')
          message: Wildcard certificates are not allowed
    usages:
      - "server auth"
  constraints:
    privateKey:
      algorithm: RSA
      minSize: 2048
  selector:
    issuerRef:
      name: letsencrypt-prod
      kind: Issuer
      group: cert-manager.io
