apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: plugin-some-example
spec:
  allowed:
    commonName:
      value: "example.com"
  plugins:
    rego:
      values:
       my-ref: "hello-world"
  selector:
    issuerRef:
      name: my-ca
      kind: Issuer
      group: cert-manager.io
