apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: plugin-some-example
spec:
  allowed:
    commonName: "example.com"
  plugins:
    some-example:
      values:
        my-ref: "hello-world"
  selector:
    issuerRef:
      name: my-ca
      kind: Issuer
      group: cert-manager.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-policy:plugin-some-example
  namespace: sandbox
rules:
- apiGroups: ["policy.cert-manager.io"]
  resources: ["certificaterequestpolicies"]
  verbs: ["use"]
  resourceNames: ["plugin-some-example"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-policy:plugin-some-example
  namespace: sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-policy:plugin-some-example
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
