apiVersion: v1

name: cert-manager-approver-policy
type: application
description: A Helm chart for cert-manager-approver-policy

home: https://github.com/cert-manager/approver-policy
maintainers:
- name: cert-manager-dev
  email: cert-manager-dev@googlegroups.com
  url: https://cert-manager.io
sources:
- https://github.com/cert-manager/approver-policy

appVersion: v0.1.0
version: v0.1.0
