# permissions for end users to view certificaterequestpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificaterequestpolicy-viewer-role
rules:
- apiGroups:
  - policy.cert-manager.io
  resources:
  - certificaterequestpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.cert-manager.io
  resources:
  - certificaterequestpolicies/status
  verbs:
  - get
