# -- Number of replicas of policy-approver to run.
replicaCount: 1

image:
  # -- Target image repository.
  repository: quay.io/jetstack/cert-manager-policy-approver
  # -- Target image version tag.
  tag: v0.1.0
  # -- Kubernetes imagePullPolicy on Deployment.
  pullPolicy: IfNotPresent

app:
  # -- Verbosity of policy-approver logging.
  logLevel: 1 # 1-5

  # -- Extra CLI arguments that will be passed to the policy-approver process.
  extraArgs: []

  # -- List if signer names that policy-approver will be given permission to
  # approve and deny. CertificateRequests referencing these signer names can be
  # processed by policy-approver. See:
  # https://cert-manager.io/docs/concepts/certificaterequest/#approval
  approveSignerNames:
  - "issuers.cert-manager.io/*"
  - "clusterissuers.cert-manager.io/*"

  metrics:
    # -- Port for exposing Prometheus metrics on 0.0.0.0 on path '/metrics'.
    port: 9402
    # -- Service to expose metrics endpoint.
    service:
      # -- Create a Service resource to expose metrics endpoint.
      enabled: true
      # -- Service type to expose metrics.
      type: ClusterIP
      # -- ServiceMonitor resource for this Service.
      servicemonitor:
        enabled: false
        prometheusInstance: default
        interval: 10s
        scrapeTimeout: 5s
        labels: {}

  readinessProbe:
    # -- Container port to expose policy-approver HTTP readiness probe on
    # default network interface.
    port: 6060

  webhook:
    # -- Host that the webhook listens on.
    host: 0.0.0.0
    # -- Port that the webhook listens on.
    port: 6443
    # -- Timeout of webhook HTTP request.
    timeoutSeconds: 5
    # -- Type of Kubernetes Service used by the Webhook
    service:
      type: ClusterIP

# -- Optional extra volume mounts. Useful for mounting custom root CAs
volumeMounts: []
#- name: my-volume-mount
#  mountPath: /etc/policy-approver/secrets

# -- Optional extra volumes.
volumes: []
#- name: my-volume
#  secret:
#    secretName: my-secret


resources: {}
  # -- Kubernetes pod resource limits for policy-approver.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # -- Kubernetes pod memory resource requests for policy-approver.
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
